extra["groupId"] = "io.github.the-best-is-best"
extra["version"] = "1.0.0"
extra["packageUrl"] = "https://github.com/the-best-is-best/Nav3Generator"
extra["issueUrl"] = "https://github.com/the-best-is-best/Nav3Generator/issues"
extra["connectionGit"] = "https://github.com/the-best-is-best/Nav3Generator.git"
extra["system"] = "GITHUB"
extra["developerName"] = "Michelle Raouf"
extra["developerNameId"] = "MichelleRaouf"
extra["developerEmail"] = "eng.michelle.raouf@gmail.com"
extra["packageDescription"] =
    "A powerful KSP-based navigation generator for Compose Multiplatform Navigation 3. It automates route definitions, polymorphic serialization, and screen mapping to provide a type-safe, boilerplate-free navigation experience across Android, iOS, Desktop, and Web."
